//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("95BBC977-73B1-4C86-8737-FAFF734E8F93")]
[assembly: AssemblyTitle("Enticify.Cs2009.Components")]
[assembly: AssemblyDescription("ConfigurableOrderPipelinesProcessor Component for Commerce Server 2009.")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCompany("Shape Factory Limited")]
[assembly: AssemblyProduct("Enticify.Cs2009.Components")]
[assembly: AssemblyCopyright("Copyright Shape Factory Limited 2013")]
[assembly: AssemblyVersion("0.4.0")]
[assembly: AssemblyFileVersion("0.4.0")]
[assembly: AssemblyDelaySign(false)]


